name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: pip3 install tweepy
    - name: Run a multi-line script
      run: python3 main.py
